### ISSUE TITLE
Make me as the nuget pakcage owner

### ISSUE THREAD

**Issue by yukozh** [PomeloFoundation/Pomelo.JsonObject#2]
My user name is `AmamiyaYuuko` thanks.

**Comment by caleblloyd** [comment]
![image](https://cloud.githubusercontent.com/assets/2414837/18497118/c96af5ca-79f9-11e6-996b-70695924d315.png)

Added you a couple days ago, do you see the invite on https://www.nuget.org/packages/Pomelo.JsonObject/

**Comment by yukozh** [comment]
Thanks
