### ISSUE TITLE
dotnet publish fail resolve dependencies

### ISSUE THREAD

**Issue by guillaumechervet** [PomeloFoundation/Pomelo.JsonObject#6]
Hi,

When I am trying to publish a self contained app. I have the errors bellow.

Do you know what can I Do?

C:\Projects\WacRequest\src\Wac.Api>dotnet publish "./Wac.Api.csproj" -o C:\testpublishwB23a\186\a\webpackages -c release -r win10-x64 -f netcoreapp2.1
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj...
  Restoring packages for C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj...
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605: Detected package downgrade: System.Diagnostics.Debug from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version.  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Diagnostics.Debug (>= 4.3.0)  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Diagnostics.Debug (>= 4.0.11) [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605: Detected package downgrade: System.IO from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version.  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.IO (>= 4.3.0)  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.IO (>= 4.1.0) [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605: Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version.  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.IO.FileSystem.Primitives (>= 4.3.0)  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem.Primitives (>= 4.0.1) [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605: Detected package downgrade: System.Resources.ResourceManager from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version.  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Resources.ResourceManager (>= 4.3.0)  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Resources.ResourceManager (>= 4.0.1) [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605: Detected package downgrade: System.Runtime.Extensions from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version.  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Runtime.Extensions (>= 4.3.0)  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Runtime.Extensions (>= 4.1.0) [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605: Detected package downgrade: System.Runtime.Handles from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version.  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Runtime.Handles (>= 4.3.0)  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem 4.0.1 -> System.Runtime.Handles (>= 4.0.1) [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605: Detected package downgrade: System.Runtime.InteropServices from 4.3.0 to 4.1.0. Reference the package directly from the project to select a different version.  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Runtime.InteropServices (>= 4.3.0)  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Xml.ReaderWriter 4.0.11 -> System.Runtime.InteropServices (>= 4.1.0) [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605: Detected package downgrade: System.Text.Encoding from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version.  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Text.Encoding (>= 4.3.0)  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Text.Encoding (>= 4.0.11) [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605: Detected package downgrade: System.Text.Encoding.Extensions from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version.  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Text.Encoding.Extensions (>= 4.3.0)  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Text.Encoding.Extensions (>= 4.0.11) [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605: Detected package downgrade: System.Threading from 4.3.0 to 4.0.11. Reference the package directly from the project to select a different version.  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Threading (>= 4.3.0)  [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj : error NU1605:  Wac.Request.Core -> Pomelo.EntityFrameworkCore.MySql 2.1.1 -> Pomelo.JsonObject 1.1.1 -> Newtonsoft.Json 9.0.1 -> System.Threading (>= 4.0.11) [C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj]
  Restore failed in 1.05 sec for C:\Projects\WacRequest\src\Wac.Request.Core\Wac.Request.Core.csproj.
  Generating MSBuild file C:\Projects\WacRequest\src\Wac.Api\obj\Wac.Api.csproj.nuget.g.props.
  Generating MSBuild file C:\Projects\WacRequest\src\Wac.Api\obj\Wac.Api.csproj.nuget.g.targets.
  Restore completed in 4.43 sec for C:\Projects\WacRequest\src\Wac.Api\Wac.Api.csproj.

Regards,

Guillaume

**Comment by mguinness** [comment]
The dependency errors stem from Newtonsoft.Json version 9.0.1 being referenced in the project file.  Try adding `<NoWarn>NU1605</NoWarn>` to Wac.Api.csproj as a short term fix.  Long term fix would be to use a newer version and maybe update target framework from netstandard1.3 to netstandard2.0 as well.

**Comment by caleblloyd** [comment]
Yes we should probably update this with every Pomelo.EntityFrameworkCore.MySql release and just bump deps.  That will be a goal of next release for Pomelo.EntityFrameworkCore.MySql.

**Comment by caleblloyd** [comment]
2.0.0 has been published, go ahead and require that in your csproj and it should fix your issue
